version: "3"
services:
  mongo:
    container_name: mongo-container
    image: mongo:3
    restart: always
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
  api:
    container_name: api-container
    image: node:18
    restart: always
    working_dir: /usr/src/surveylab-api
    command: bash -c "npm install && npm run debug"
    environment:
      - MONGO_URL=mongodb://mongo:27017/surveylab-api
    volumes:
      - ./dist:/usr/src/surveylab-api/dist
      - ./package.json:/usr/src/surveylab-api/package.json
    ports:
      - "5050:5050"
      - "9222:9222"
    links:
      - mongo
